insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (1, 166, '2$ Off Next Purchase.', 2.4, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (2, 82, '2$ Off Next Purchase.', 1.2, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (3, 142, '2$ Off Next Purchase.', 1.4, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (4, 17, '2$ Off Next Purchase.', 2.6, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (5, 36, '10% Discount', 2.6, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (6, 58, 'Free Class Pass', 2.2, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (7, 158, '2$ Off Next Purchase.', 2.0, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (8, 45, '2$ Off Next Purchase.', 2.1, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (9, 176, '2$ Off Next Purchase.', 1.7, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (10, 113, '10% Discount', 1.8, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (11, 171, 'Free Class Pass', 2.3, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (12, 73, '2$ Off Next Purchase.', 2.1, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (13, 57, '2$ Off Next Purchase.', 1.1, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (14, 178, '2$ Off Next Purchase.', 2.2, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (15, 18, '10% Discount', 2.1, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (16, 136, '2$ Off Next Purchase.', 1.5, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (17, 81, 'Free Class Pass', 2.2, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (18, 172, '2$ Off Next Purchase.', 2.4, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (19, 129, '10% Discount', 2.1, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (20, 141, '10% Discount', 1.0, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (21, 73, '10% Discount', 2.0, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (22, 12, '2$ Off Next Purchase.', 2.1, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (23, 71, 'Free Class Pass', 2.2, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (24, 18, 'Free Class Pass', 1.9, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (25, 156, '2$ Off Next Purchase.', 2.4, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (26, 156, '10% Discount', 2.6, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (27, 1, 'Free Class Pass', 2.5, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (28, 6, '10% Discount', 1.6, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (29, 14, '2$ Off Next Purchase.', 1.4, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (30, 168, '2$ Off Next Purchase.', 2.2, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (31, 157, '2$ Off Next Purchase.', 1.7, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (32, 130, 'Free Class Pass', 1.6, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (33, 157, 'Free Class Pass', 2.9, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (34, 53, '10% Discount', 1.4, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (35, 46, '2$ Off Next Purchase.', 2.2, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (36, 145, '2$ Off Next Purchase.', 1.6, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (37, 18, '10% Discount', 2.2, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (38, 64, '2$ Off Next Purchase.', 2.7, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (39, 179, 'Free Class Pass', 2.1, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (40, 34, 'Free Class Pass', 1.8, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (41, 67, '10% Discount', 1.4, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (42, 147, '2$ Off Next Purchase.', 2.5, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (43, 136, 'Free Class Pass', 2.9, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (44, 116, 'Free Class Pass', 2.0, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (45, 102, '10% Discount', 1.5, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (46, 80, '10% Discount', 2.7, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (47, 57, 'Free Class Pass', 1.2, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (48, 103, '2$ Off Next Purchase.', 2.5, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (49, 42, '10% Discount', 2.5, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (50, 45, 'Free Class Pass', 2.4, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (51, 153, '10% Discount', 2.3, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (52, 108, 'Free Class Pass', 1.4, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (53, 103, '2$ Off Next Purchase.', 2.5, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (54, 164, '10% Discount', 2.3, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (55, 21, '2$ Off Next Purchase.', 1.7, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (56, 170, 'Free Class Pass', 1.3, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (57, 41, '10% Discount', 1.7, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (58, 158, '10% Discount', 2.1, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (59, 34, 'Free Class Pass', 2.4, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (60, 18, '2$ Off Next Purchase.', 3.0, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (61, 29, '2$ Off Next Purchase.', 2.4, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (62, 95, 'Free Class Pass', 1.3, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (63, 90, 'Free Class Pass', 2.0, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (64, 179, '10% Discount', 2.7, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (65, 70, '10% Discount', 1.1, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (66, 133, 'Free Class Pass', 1.2, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (67, 10, '2$ Off Next Purchase.', 2.0, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (68, 146, '10% Discount', 2.8, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (69, 121, '10% Discount', 2.1, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (70, 155, 'Free Class Pass', 1.2, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (71, 87, '10% Discount', 1.8, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (72, 17, 'Free Class Pass', 2.7, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (73, 98, '2$ Off Next Purchase.', 1.2, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (74, 91, '10% Discount', 1.3, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (75, 152, '2$ Off Next Purchase.', 2.3, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (76, 20, '2$ Off Next Purchase.', 2.4, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (77, 111, 'Free Class Pass', 1.5, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (78, 43, '10% Discount', 1.6, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (79, 57, '10% Discount', 1.1, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (80, 77, '10% Discount', 1.3, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (81, 156, '2$ Off Next Purchase.', 2.6, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (82, 60, '10% Discount', 1.1, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (83, 90, 'Free Class Pass', 2.4, '2/23/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (84, 60, 'Free Class Pass', 1.6, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (85, 26, '2$ Off Next Purchase.', 1.4, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (86, 141, '2$ Off Next Purchase.', 1.4, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (87, 99, '2$ Off Next Purchase.', 2.3, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (88, 133, 'Free Class Pass', 1.8, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (89, 61, '10% Discount', 2.6, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (90, 123, '10% Discount', 2.4, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (91, 169, 'Free Class Pass', 1.0, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (92, 45, '10% Discount', 1.8, '2/24/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (93, 65, 'Free Class Pass', 1.7, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (94, 56, 'Free Class Pass', 2.7, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (95, 1, '2$ Off Next Purchase.', 2.7, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (96, 161, '2$ Off Next Purchase.', 1.7, '2/22/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (97, 177, '10% Discount', 2.0, '2/26/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (98, 120, '10% Discount', 1.2, '2/25/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (99, 9, '10% Discount', 1.7, '2/27/2024');
insert into "rewardsprogram" (reward_id, member_id, reward_description, reward_amount, reward_date) values (100, 36, 'Free Class Pass', 3.0, '2/26/2024');
